"""Initial Migration

Revision ID: 0b44d618bfdf
Revises: 7a7c6a57df65
Create Date: 2022-05-10 17:21:49.142846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b44d618bfdf'
down_revision = '7a7c6a57df65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pitch_title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('posted', sa.DateTime(), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'comment', 'pitches', ['pitch_id'], ['id'])
    op.create_foreign_key(None, 'dislike', 'pitches', ['pitch_id'], ['id'])
    op.create_foreign_key(None, 'likes', 'pitches', ['pitch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'dislike', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_table('pitches')
    # ### end Alembic commands ###
