"""Initial Migration

Revision ID: a71c9a8885f9
Revises: c9866ea291b7
Create Date: 2022-05-10 08:50:16.686153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a71c9a8885f9'
down_revision = 'c9866ea291b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comment', 'pitches', ['pitch_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'users', ['user_id'], ['id'])
    op.add_column('pitches', sa.Column('content', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('category', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('posted', sa.DateTime(), nullable=True))
    op.add_column('pitches', sa.Column('author', sa.Integer(), nullable=True))
    op.drop_constraint('pitches_user_id_fkey', 'pitches', type_='foreignkey')
    op.create_foreign_key(None, 'pitches', 'users', ['author'], ['id'])
    op.drop_column('pitches', 'pitch_date')
    op.drop_column('pitches', 'user_id')
    op.drop_column('pitches', 'pitch_category')
    op.drop_column('pitches', 'pitch_content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch_content', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('pitch_category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('pitch_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.create_foreign_key('pitches_user_id_fkey', 'pitches', 'users', ['user_id'], ['id'])
    op.drop_column('pitches', 'author')
    op.drop_column('pitches', 'posted')
    op.drop_column('pitches', 'category')
    op.drop_column('pitches', 'content')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    # ### end Alembic commands ###
